# Generated by Django 6.0.4 on 2026-04-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='created_at',
        ),
        migrations.AddField(
            model_name='capsule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='capsules/'),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
