# Generated by Django 6.0.4 on 2026-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_remove_capsule_created_at_capsule_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='share_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
